subcomponents:
  spartan-service:
    namespace: services
    config:
      replicaCount: 1
      minReadySeconds: 5
      strategyType: RollingUpdate
      image:
        repository: andrebriggs.azurecr.io/andrebriggs/spartan-app
        tag: "20190427.3"
        pullPolicy: IfNotPresent
      service:
        port: 80
        containerPort: 8080